[package]
name = "perp-maker"
version.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
bigdecimal.workspace = true
clap.workspace = true
haneul-crypto.workspace = true
haneul-sdk-types.workspace = true
haneul-transaction-builder.workspace = true
num-bigint.workspace = true
perp-bot-common.workspace = true
perp-engine.workspace = true
prometheus.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true

[dev-dependencies]
bcs.workspace = true

[[bin]]
name = "perp-maker"
path = "src/main.rs"
