[package]
name = "perp-bot-common"
version.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
bigdecimal.workspace = true
clap.workspace = true
diesel.workspace = true
diesel-async.workspace = true
haneul-crypto.workspace = true
haneul-rpc.workspace = true
haneul-sdk-types.workspace = true
haneul-transaction-builder.workspace = true
hex.workspace = true
num-bigint.workspace = true
prometheus.workspace = true
prost-types.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
bcs.workspace = true
